title: Patrick Bryant's research lab
email:  patrick.bryant@scilifelab.se
description: >- # this means to ignore newlines until "baseurl:"
    We build the technology of the future.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  patrickbryant1

# Build settings
theme: minima
plugins:
  - jekyll-feed
